#!/bin/bash -e

cd ../opt/django_starburger_docker/
docker compose down
git pull
docker compose up -d --build
systemctl daemon-reload
git_commit=$(git show -s --format=%H)

cd ~
echo "{\"revision\":\"$git_commit\",\"environment\":\"production\",\"status\":\"succeeded\",\"local_username\":\"$USER\"}" |  \
  http POST https://api.rollbar.com/api/1/deploy \
  X-Rollbar-Access-Token:$(cat .env) \
  accept:application/json \
  content-type:application/json

echo "Деплой завершен успешно"
