version: "3.9"

services:
  postgresdb:
    image: postgres:12.0-alpine
    container_name: postgres_db
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  frontend:
    container_name: parcel
    build: frontend
    volumes:
      - bundles:/opt/app/bundles

  backend:
    container_name: django
    build: backend
    depends_on:
      - postgresdb
      - frontend
    volumes:
      - bundles:/starburger/bundles
      - db_data:/starburger/db_data
      - static:/starburger/static
      - media:/starburger/media
    env_file:
      - .env
    command: >
      bash -c "./manage.py migrate && ./manage.py collectstatic --noinput && gunicorn -w 3 -b :8000 star_burger.wsgi:application"

  web:
    container_name: nginx_server
    build: nginx
    depends_on:
      - backend
    volumes:
      - static:/opt/starburger/static/
      - media:/opt/starburger/media/
    ports:
      - 80:80

volumes:
  db_data:
  bundles:
  static:
  media:
