version: "3.9"

services:
  postgresdb:
    image: postgres:12.0-alpine
    container_name: postgres_db
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - django_starburger_docker

  frontend:
    container_name: parcel
    build: frontend
    volumes:
      - bundles:/opt/app/bundles
    networks:
      - django_starburger_docker

  backend:
    container_name: django
    build: backend
    depends_on:
      - postgresdb
      - frontend
    volumes:
      - bundles:/starburger/bundles
      - db_data:/starburger/db_data
      - /var/www/starburger:/starburger/static
      - /var/www/starburger:/starburger/media
    env_file:
      - .env
    ports:
      - 8080:8080
    networks:
      - host
      - django_starburger_docker
    command: >
      bash -c "./manage.py migrate && ./manage.py collectstatic --noinput && gunicorn -w 3 -b :8000 star_burger.wsgi:application"

volumes:
  db_data:
  bundles:

networks:
  django_starburger_docker:
