version: "3.5"

services:
  db:
    image: postgres:12.0-alpine
    container_name: postgres_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB-test_k8s}
      POSTGRES_USER: ${POSTGRES_USER-test_k8s}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-OwOtBep9Frut}

  frontend:
    container_name: parcel
    build: frontend

  bakcend:
    container_name: django
    build: bakcend
    depends_on:
      - db
      - frontend


volumes:
  db_data:
  staticfiles: