# Generated by Django 3.2.15 on 2023-09-12 10:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('product', models.ManyToManyField(related_name='order', to='foodcartapp.Product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Состав заказа',
                'verbose_name_plural': 'Состав заказов',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='телефон')),
                ('address', models.TextField(blank=True, max_length=200, verbose_name='Адрес')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='foodcartapp.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
