# Generated by Django 3.2.15 on 2023-09-15 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20230912_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='in_order', to='foodcartapp.product', verbose_name='Товар'),
            preserve_default=False,
        ),
    ]
