# Generated by Django 3.2.15 on 2023-10-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_data_calculate_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order_status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('COOK', 'Приготовление'), ('DELIVERY', 'Доставка'), ('READY', 'Исполнен')], default='NEW', max_length=10),
        ),
    ]
