# Generated by Django 3.2.15 on 2023-10-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_customer_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='order_status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('COOK', 'Приготовление'), ('DELIVERY', 'Доставка'), ('READY', 'Исполнен')], db_index=True, default='NEW', max_length=10),
        ),
    ]
