# Generated by Django 3.2.15 on 2023-10-19 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20231019_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='call_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время звонка клиенту'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время доставки заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 10, 57, 6, 107598, tzinfo=utc), verbose_name='Время регистрации заказа'),
        ),
    ]
