# Generated by Django 3.2.15 on 2023-10-20 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cooking_restaurant',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='foodcartapp.restaurant', verbose_name='Какой ресторан готовит'),
            preserve_default=False,
        ),
    ]
