# Generated by Django 3.2.15 on 2023-10-20 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cooking_restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='foodcartapp.restaurant', verbose_name='Какой ресторан готовит'),
        ),
    ]
