# Generated by Django 4.2.7 on 2023-11-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('OFFLINE', 'Оплата курьеру'), ('ONLINE', 'Оплачен на сайте'), ('NOT_SET', 'Не задано')], db_index=True, default='NOT_SET', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
