# Generated by Django 4.2.7 on 2023-11-04 05:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0004_addresscoordinates_coordinates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresscoordinates',
            name='coordinates_date',
            field=models.DateField(default=datetime.date(2023, 11, 4), verbose_name='Дата запроса координат'),
        ),
        migrations.AlterField(
            model_name='addresscoordinates',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='addresscoordinates',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
    ]
