# Generated by Django 4.2.7 on 2023-11-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0005_alter_addresscoordinates_coordinates_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresscoordinates',
            name='address',
            field=models.CharField(max_length=100, unique=True, verbose_name='Адрес'),
        ),
    ]
