# Generated by Django 3.2.15 on 2023-12-04 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0007_alter_addresscoordinates_coordinates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresscoordinates',
            name='coordinates_date',
            field=models.DateField(default=datetime.date(2023, 12, 4), verbose_name='Дата запроса координат'),
        ),
    ]
